# DESAFIO 099

# FAÇA UM PROGRAMA QUE TENHA UMA FUNÇÃO CHAMADA
# maior(), QUE RECEBA VÁRIOS PARÂMETROS COM
# VALORES INTEIROS.

# SEU PROGRAMA TEM QUE ANALISAR TODOS OS VALORES
# E DIZER QUAL DELES É O MAIOR.
