# DESAFIO 100

# FAÇA UM PROGRAMA QUE TENHA UMA LISTA CHAMADA
# NÚMEROS E DUAS FUNÇÕES CHAMADAS sorteia() E
# somaPar(). A PRIMEIRA FUNÇÃO VAI SORTEAR 5
# NÚMEROS E VAI COLOCÁ-LOS DENTRO DA LISTA E
# A SEGUNDA FUNÇÃO VAI MOSTRAR A SOMA ENTRE
# TODOS OS VALORES PARES SORTEADOS PELA FUNÇÃO
# ANTERIOR.
